def count_dna():
    seq = input("What is your sequence?")
    print("My sequence is " + seq)



#s = 'GCCGGCGGAAAATTCGATTTCAGACTAATAGGCGACCTTTCACCCTCGATCCCGAGTCAACGTGATTAGTATTAGAGCTTTAGATGTCTGACTGTATAACTAAAACTGCATGCATGAAATGTCGTTATTCTTCCTTCGACTCCTGTAGACCGGCAGTCGATCGACGTAATCTAATGGCACCACGAGAATTGTCCTCCCGACTCTCTTGATTTAGGATACCACAATTACAGCTTGCGGCTAAGTAAAGCTTAATAGAGCCTGATCGTGCAGATAAGCAGGCCGCTAGCGTAGGTCCTGACGTCCCGATACGCGTTTCTAACACGCGTGCTGTCACATTTGTCTACAAGCTCGTGTCATAGTGTCCGCGCCCGGGAACAAGAATCACGCTTAAGACCCACCGCCTTGCTCAACTAGCCGTCCTGATAGAACCTGTGGCGAAGCTCCGTTTTATCGAAGTAGACGTCCATAGTTTGAGAGGGGCTCGAGATTTCGTTTCCGAAGAAACGGGAAGCTCCCCCTAGCAAACTTGTCGGCACACGACGCCTGTTGGTTTGTGAGGAATTAACCCGTTCGATGAGAGTGGCTTCTGATAAAGTGCGAAAATTTCATGAATTACGTGTTCGTTCGTTAGACCATGGGATATTCTTGACAACACGTGACATCAGAACTGGCAATTTACTACAACCAAGAGCACACGTGGCGCATTGTCTCGTTCAGTACAAGTTTTATAGAAAGTTGAGCAACAGAGAAGGTACGGTGGCCGGCTTGGGCCTGGGCTTCATGAAACGTTTGCAGGGTGTATATATTTAAGTAGGTGAAGCTCCAGCCGGATTAATGTGATGGGCGGCTGGTAGGCCGTCGCATTATGGCTGTCTGACGACGGGACAATAAGAATCTTAGGTTTCAACATACAACTGGACTGCCGGGCAGGGGTACCTGAATACCGACAAGGCCACCATAGGGG'

    a_count = seq.count('A')
    t_count = seq.count('T')
    g_count = seq.count('G')
    c_count = seq.count('C')

    print('A count is ' + str(a_count))
    print('T count is ' + str(t_count))
    print('G count is ' + str(g_count))
    print('C count is ' + str(c_count))

count_dna()
